#ifndef SPDLOG_ISSUE_973_THREAD_HOLDER_EXPORT_HPP
#define SPDLOG_ISSUE_973_THREAD_HOLDER_EXPORT_HPP

#ifdef SPDLOG_ISSUE_973_BUILD_SHARED
#define SPDLOG_ISSUE_973_API __declspec(dllexport)
#else
#define SPDLOG_ISSUE_973_API __declspec(dllimport)
#endif

#endif // SPDLOG_ISSUE_973_THREAD_HOLDER_EXPORT_HPP
